### ISSUE TITLE
Brute can't break reinforced plasteel walls

### ISSUE THREAD

**Issue by chesse20** [DS-13-Dev-Team/DS13-2.0#140] opened 2023-09-09 22:19 UTC
## Testmerges:
[#128: 'Aegis7' by blackwolf602 at commit 6496daf920](https://github.com/DS-13-Dev-Team/DS13-2.0/pull/128)
[#131: 'Redbot' by RegJoe at commit ba2c73fd0d](https://github.com/DS-13-Dev-Team/DS13-2.0/pull/131)

## Reproduction:
Be Brute

Attack reinforced walls

They take no damage

**Comment by DTraitor** [comment] 2023-09-15 15:17
Did you use slam ability or just punched the wall?

**Comment by chesse20** [comment] 2023-09-17 18:31
> Did you use slam ability or just punched the wall?
Slam

**Comment by MisterGrimm** [comment] 2023-11-02 07:30
This is not a bug, but rather a unintended consequence with wall and airlock code. Walls and airlocks have a "deflection" rating, where if the damage is under a stated amount it does no damage to the structure. Necros that are supposed to be able to destroy walls need special interactions with walls, to artificially increase their damage to overcome the deflection.

**Comment by MisterGrimm** [comment] 2024-01-02 02:08
Fixed in PR #145

**Closed by MisterGrimm** 2024-01-02 02:08 UTC
